<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Project Mental Health and Screen Time</title>

<script src="site_libs/header-attrs-2.30/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="projecten.html">Projects</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://www.linkedin.com/in/thomas-elzinga-9804463b1">
    <span class="fa fa-brands fa-linkedin"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/Samoht-git/my_website">
    <span class="fa fa-brands fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Project Mental Health and Screen Time</h1>

</div>


<div id="analysis-of-screen-time-and-mental-health-students"
class="section level1">
<h1>Analysis of screen time and mental health students</h1>
<p>Name student: Thomas Elzinga</p>
<p>Date: 12-11-2025</p>
<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>In today’s digital era, there is a growing concern about the impact
of social media on mental well-being. Managing screen time, reducing
exposure to negative content and making more genuine connections with
people around you. Therefore, understanding the relationship between
social media usage patterns and mental health indicators is crucial. The
dataset analyzed in this report consists of a comma-separated values
(CSV) file containing data from 500 social media users. For each
individual, variables such as daily screen time, number of platforms
used, frequency of interactions, mood scores, and self-reported stress
levels are recorded. Additionally, users are categorized into different
demographic groups, such as age ranges, gender, to facilitate
comparative analysis.</p>
</div>
<div id="dataset" class="section level2">
<h2>Dataset</h2>
<p>The dataset originates from <a
href="https://www.kaggle.com/datasets/prince7489/mental-health-and-social-media-balance-dataset">Kaggle</a>.</p>
</div>
<div id="aim" class="section level2">
<h2>Aim</h2>
<p>The primary goal of the data analysis of this dataset is to evaluate
and compare the relationship between social media usage patterns and
mental health indicators across different demographic groups and user
behaviors. The analysis specifically aims to provide the following
insights:</p>
<p>• Identification of the demographic group(s) with the highest average
screen time and corresponding mental health scores. This helps determine
which user groups may be more vulnerable to the negative impacts of
excessive social media use.</p>
<p>• Identification of the specific social media platform or activity
type associated with the highest amount of average daily screen
time.</p>
<p>• Identification of correlation between average daily screen time and
mental well being(Rating happiness score, stress level and sleep
quality)</p>
</div>
<div id="loading-libraries" class="section level2">
<h2>Loading libraries</h2>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching core tidyverse packages ───
## ✔ dplyr     1.1.4     ✔ readr     2.1.5
## ✔ forcats   1.0.1     ✔ stringr   1.5.2
## ✔ ggplot2   4.0.0     ✔ tibble    3.3.0
## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
## ✔ purrr     1.1.0     
## ── Conflicts ── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()
## ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
<pre class="r"><code>library(kableExtra)</code></pre>
<pre><code>## 
## Attaching package: &#39;kableExtra&#39;
## 
## The following object is masked from &#39;package:dplyr&#39;:
## 
##     group_rows</code></pre>
</div>
<div id="data-import" class="section level2">
<h2>Data Import</h2>
<p>First, the data was viewed in Visual Studio Code. To make the
identification of different columns more clear, the rainbow csv
extension was used. A screenshot of the import can be seen below.</p>
<div class="float">
<img src="data_import_VScode_1.png" alt="data" />
<div class="figcaption">data</div>
</div>
<p>Looking at the file, it’s a CSV file with the comma as the column
separator and decimals separated by a period.<br />
A dataframe was created and the file was loaded the in R via
<code>read_csv</code>:</p>
<pre class="r"><code>file_path &lt;- &quot;./Mental_Health_and_Social_Media_Balance_Dataset.csv&quot;
df1 &lt;- read_csv(file_path)</code></pre>
<pre><code>## Rows: 500 Columns: 10
## ── Column specification ────────────────
## Delimiter: &quot;,&quot;
## chr (3): User_ID, Gender, Social_Media_Platform
## dbl (7): Age, Daily_Screen_Time(hrs), Sleep_Quality(1-10), Stress_Level(1-10...
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<pre class="r"><code>head(df1)</code></pre>
<pre><code>## # A tibble: 6 × 10
##   User_ID   Age Gender `Daily_Screen_Time(hrs)` `Sleep_Quality(1-10)`
##   &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;                     &lt;dbl&gt;                 &lt;dbl&gt;
## 1 U001       44 Male                        3.1                     7
## 2 U002       30 Other                       5.1                     7
## 3 U003       23 Other                       7.4                     6
## 4 U004       36 Female                      5.7                     7
## 5 U005       34 Female                      7                       4
## 6 U006       38 Male                        6.6                     5
## # ℹ 5 more variables: `Stress_Level(1-10)` &lt;dbl&gt;,
## #   Days_Without_Social_Media &lt;dbl&gt;, `Exercise_Frequency(week)` &lt;dbl&gt;,
## #   Social_Media_Platform &lt;chr&gt;, `Happiness_Index(1-10)` &lt;dbl&gt;</code></pre>
<p>All of the data was correctly imported, the dataset does not contain
any missing data and there are no duplicates. All of the columns are
imported as the correct data type. Numeric data is imported as
dbl(double) and words are imported as chr(character). Therefore no data
cleaning was needed and the analysis could proceed.</p>
</div>
<div id="data-cleaning" class="section level2">
<h2>Data cleaning</h2>
<p>There was no need for cleaning the dataset for this analysis.
Therefore the data was modified to demonstrate and show what would have
needed to be done if the file contained duplicates and blanks, the
original file was modified. The modified file was cleaned for
demonstrative purposes.</p>
<pre class="r"><code>modified_file &lt;- &quot;./Mental_Health_and_Social_Media_Balance_Dataset_Modified_2.csv&quot;
df9 &lt;- read_csv(modified_file)</code></pre>
<pre><code>## Rows: 501 Columns: 10
## ── Column specification ────────────────
## Delimiter: &quot;,&quot;
## chr (3): User_ID, Gender, Social_Media_Platform
## dbl (7): Age, Daily_Screen_Time(hrs), Sleep_Quality(1-10), Stress_Level(1-10...
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<pre class="r"><code>head(df9)</code></pre>
<pre><code>## # A tibble: 6 × 10
##   User_ID   Age Gender `Daily_Screen_Time(hrs)` `Sleep_Quality(1-10)`
##   &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;                     &lt;dbl&gt;                 &lt;dbl&gt;
## 1 U001       44 Male                        3.1                     7
## 2 U002       30 Other                       5.1                     7
## 3 U003       23 Other                       7.4                     6
## 4 U004       36 Female                      5.7                     7
## 5 U005       34 Female                      7                       4
## 6 U006       38 Male                        6.6                     5
## # ℹ 5 more variables: `Stress_Level(1-10)` &lt;dbl&gt;,
## #   Days_Without_Social_Media &lt;dbl&gt;, `Exercise_Frequency(week)` &lt;dbl&gt;,
## #   Social_Media_Platform &lt;chr&gt;, `Happiness_Index(1-10)` &lt;dbl&gt;</code></pre>
<p>First the amount of blanks in the dataframe should be identified, by
counting the amount of NA values in the dataframe.</p>
<pre class="r"><code>sum(is.na.data.frame(df9))</code></pre>
<pre><code>## [1] 1</code></pre>
<p>The amount of missing values in this dataframe is 1</p>
<p>Now the NA value has to idendified, the position of the missing value
in the dataframe should be determined.</p>
<pre class="r"><code>which(is.na(df9), arr.ind=TRUE)</code></pre>
<pre><code>##      row col
## [1,] 113   2</code></pre>
<p>The NA value seems to be located on row 113 and column 2.</p>
<p>Now the row can be shown by filtering on column 2</p>
<pre class="r"><code>df9 %&gt;%
  filter(is.na(Age))</code></pre>
<pre><code>## # A tibble: 1 × 10
##   User_ID   Age Gender `Daily_Screen_Time(hrs)` `Sleep_Quality(1-10)`
##   &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;                     &lt;dbl&gt;                 &lt;dbl&gt;
## 1 U113       NA Female                      4.3                     6
## # ℹ 5 more variables: `Stress_Level(1-10)` &lt;dbl&gt;,
## #   Days_Without_Social_Media &lt;dbl&gt;, `Exercise_Frequency(week)` &lt;dbl&gt;,
## #   Social_Media_Platform &lt;chr&gt;, `Happiness_Index(1-10)` &lt;dbl&gt;</code></pre>
<p>Then there was checked if there were any duplicates</p>
<pre class="r"><code>sum(duplicated(df9))</code></pre>
<pre><code>## [1] 1</code></pre>
<p>There seems to be one duplicate in this dataframe</p>
<p>Now the duplicate row in this dataframe needs to be identified.</p>
<pre class="r"><code>df9 %&gt;%
  group_by_all() %&gt;%
  filter(n()&gt;1) %&gt;%
  ungroup()</code></pre>
<pre><code>## # A tibble: 2 × 10
##   User_ID   Age Gender `Daily_Screen_Time(hrs)` `Sleep_Quality(1-10)`
##   &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;                     &lt;dbl&gt;                 &lt;dbl&gt;
## 1 U136       47 Female                      2.9                     8
## 2 U136       47 Female                      2.9                     8
## # ℹ 5 more variables: `Stress_Level(1-10)` &lt;dbl&gt;,
## #   Days_Without_Social_Media &lt;dbl&gt;, `Exercise_Frequency(week)` &lt;dbl&gt;,
## #   Social_Media_Platform &lt;chr&gt;, `Happiness_Index(1-10)` &lt;dbl&gt;</code></pre>
<p>There were two duplicate rows in this dataframe, U136 seems to be 2
times in this dataframe.</p>
<p>The dataframe needs to be cleaned by removing one of the rows.</p>
<pre class="r"><code>which(duplicated(df9), arr.ind=TRUE)</code></pre>
<pre><code>## [1] 137</code></pre>
<p>Rows 113 and 137 needed to be removed</p>
<pre class="r"><code>df10 &lt;- df9[-c(113, 137), ]
df10</code></pre>
<pre><code>## # A tibble: 499 × 10
##    User_ID   Age Gender `Daily_Screen_Time(hrs)` `Sleep_Quality(1-10)`
##    &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;                     &lt;dbl&gt;                 &lt;dbl&gt;
##  1 U001       44 Male                        3.1                     7
##  2 U002       30 Other                       5.1                     7
##  3 U003       23 Other                       7.4                     6
##  4 U004       36 Female                      5.7                     7
##  5 U005       34 Female                      7                       4
##  6 U006       38 Male                        6.6                     5
##  7 U007       26 Female                      7.8                     4
##  8 U008       26 Female                      7.4                     5
##  9 U009       39 Male                        4.7                     7
## 10 U010       39 Female                      6.6                     6
## # ℹ 489 more rows
## # ℹ 5 more variables: `Stress_Level(1-10)` &lt;dbl&gt;,
## #   Days_Without_Social_Media &lt;dbl&gt;, `Exercise_Frequency(week)` &lt;dbl&gt;,
## #   Social_Media_Platform &lt;chr&gt;, `Happiness_Index(1-10)` &lt;dbl&gt;</code></pre>
<p>Rows 113 and 137 are removed and a new cleaned dataframe has been
created</p>
<p>This can be controlled by using the filter functions on the new
dataframe</p>
<pre class="r"><code>sum(is.na.data.frame(df10))</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code>sum(duplicated(df10))</code></pre>
<pre><code>## [1] 0</code></pre>
<p>Both values are zero so in the new dataframe no more NA values or
duplicates remain</p>
</div>
<div
id="checking-the-mean-median-minmax-and-standard-deviation-of-the-daily-screen-time-of-all-users-combined"
class="section level2">
<h2>Checking the mean, median, min/max and standard deviation of the
daily screen time of all users combined</h2>
<p>For the rest of the analysis, the orignal dataset was used. First a
standard analysis was performed on the mean, min/max and standard
deviation of the data screen time.</p>
<pre class="r"><code>#mean
mean(df1$`Daily_Screen_Time(hrs)`)</code></pre>
<pre><code>## [1] 5.53</code></pre>
<pre class="r"><code>#standard deviation
sd(df1$`Daily_Screen_Time(hrs)`)</code></pre>
<pre><code>## [1] 1.734877</code></pre>
<pre class="r"><code>#median
median(df1$`Daily_Screen_Time(hrs)`)</code></pre>
<pre><code>## [1] 5.6</code></pre>
<pre class="r"><code>#minimum
min(df1$`Daily_Screen_Time(hrs)`)</code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code>#maximum
max(df1$`Daily_Screen_Time(hrs)`)</code></pre>
<pre><code>## [1] 10.8</code></pre>
<p>There was found that the average screen time of all users was 5,53
hours. The median was 5,6 hours, which gives a good idea of the
distribution of the data. The mean and average are close, this means
that the amount of users having more or less than the average daily
screen time are almost the same. There were no users with less than 1
hour of screen time and the highest amount of screen time was 10,8 hours
a day.</p>
</div>
<div
id="identification-of-the-demographic-groups-with-the-highest-average-screen-time"
class="section level2">
<h2>Identification of the demographic groups with the highest average
screen time</h2>
<p>To identify which of the genders has the highest average amount of
screen time, the averages of each gender needed to be calculated. The
function summarize_each and mean where used to identify the genders and
calculate the average daily screen time of each gender.</p>
<pre class="r"><code>df2 &lt;- df1 %&gt;%
  group_by(Gender) %&gt;%
  summarise(across(`Daily_Screen_Time(hrs)`, mean)) 
df2</code></pre>
<pre><code>## # A tibble: 3 × 2
##   Gender `Daily_Screen_Time(hrs)`
##   &lt;chr&gt;                     &lt;dbl&gt;
## 1 Female                     5.51
## 2 Male                       5.59
## 3 Other                      5.07</code></pre>
<pre class="r"><code>plot1 &lt;- df2 %&gt;% ggplot(aes(x = Gender, y = `Daily_Screen_Time(hrs)`)) +
  geom_bar(stat=&quot;identity&quot;, fill=&quot;steelblue&quot;) +
  labs(title=&quot;Average daily screen time for each gender&quot;) +
  theme(axis.text.x = element_text(angle = 90, hjust=1, vjust=0.5)) +
  ylab(&quot;Average daily screen time(hrs)&quot;) +
  ylim(c(0, 6))
plot1</code></pre>
<p><img src="projecten_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>In this chart can be seen that males have the highest average daily
screen time, followed by females and with Others having the lowest
average screen time. To gain more insight in the distribution of the
average screen time a boxplot was created.</p>
<pre class="r"><code>plot2 &lt;- df1 %&gt;%
  ggplot(aes(x = Gender, y = `Daily_Screen_Time(hrs)`)) + 
  geom_boxplot() +
  labs(title=&quot;Average daily screen time for each gender&quot;) +
  theme(axis.text.x = element_text(angle = 90, hjust=1, vjust=0.5)) +
  ylab(&quot;Daily screen time(hrs)&quot;) +
  ylim(c(0, 12.5))
plot2</code></pre>
<p><img src="projecten_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>In this boxplot can be seen that Males still rank highest in average
daily screen time. The difference between Males and females is not very
big. Males and females seem both to be distributed along a broad
spectrum of data. With females having a larger error rate and standard
deviation. The minum and maximum of Females seem to be higher than the
min and max of Males. The gender Other seems to have a more equal
distribution of its data and does not have large minimum are maximum
values.</p>
</div>
<div
id="finding-the-correlation-between-daily-screen-time-and-mental-health-indicators"
class="section level2">
<h2>Finding the correlation between daily screen time and mental health
indicators</h2>
<p>To find the correlation between daily screen time and mental health
indicators, 3 factors were measured. Those indicators are; happines
index, sleep quality and stress levels. First 3 dataframes were made
consisting of average daily screen time and one of the health indicator
factors.</p>
<pre class="r"><code>#dataframe sleep quality
df3 &lt;- df1 %&gt;%
  group_by(`Sleep_Quality(1-10)`) %&gt;%
  summarise(across(`Daily_Screen_Time(hrs)`, mean)) 
df3</code></pre>
<pre><code>## # A tibble: 9 × 2
##   `Sleep_Quality(1-10)` `Daily_Screen_Time(hrs)`
##                   &lt;dbl&gt;                    &lt;dbl&gt;
## 1                     2                     9.8 
## 2                     3                     8.19
## 3                     4                     7.41
## 4                     5                     6.76
## 5                     6                     5.78
## 6                     7                     4.89
## 7                     8                     4.15
## 8                     9                     3.01
## 9                    10                     2.97</code></pre>
<pre class="r"><code>#dataframe stress levels
df4 &lt;- df1 %&gt;%
  group_by(`Stress_Level(1-10)`) %&gt;%
  summarise(across(`Daily_Screen_Time(hrs)`, mean)) 
df4</code></pre>
<pre><code>## # A tibble: 9 × 2
##   `Stress_Level(1-10)` `Daily_Screen_Time(hrs)`
##                  &lt;dbl&gt;                    &lt;dbl&gt;
## 1                    2                     3   
## 2                    3                     2.7 
## 3                    4                     3.41
## 4                    5                     4.06
## 5                    6                     5.11
## 6                    7                     5.71
## 7                    8                     6.77
## 8                    9                     7.63
## 9                   10                     8.2</code></pre>
<pre class="r"><code>#dataframe happiness index
df5 &lt;- df1 %&gt;%
  group_by(`Happiness_Index(1-10)`) %&gt;%
  summarise(across(`Daily_Screen_Time(hrs)`, mean)) 
df5</code></pre>
<pre><code>## # A tibble: 7 × 2
##   `Happiness_Index(1-10)` `Daily_Screen_Time(hrs)`
##                     &lt;dbl&gt;                    &lt;dbl&gt;
## 1                       4                     9.53
## 2                       5                     7.64
## 3                       6                     7.34
## 4                       7                     6.59
## 5                       8                     5.98
## 6                       9                     5.26
## 7                      10                     4.08</code></pre>
<p>The dataframes were plotted in 3 linegraphs. Each line graph has the
daily average screen time on the y-axis and on of the health factors
1-10 on the x-axis.</p>
<pre class="r"><code>library(ggplot2)
#plot happiness index
ggplot(data=df5, aes(x=`Happiness_Index(1-10)`, y=`Daily_Screen_Time(hrs)`, group=1)) +
  geom_line(color=&quot;blue&quot;)+
  geom_point() +
  ylab(&quot;Daily screen time(hrs)&quot;) +
  xlab(&quot;Happiness index&quot;) +
  ylim(c(0, 10)) +
  xlim(c(4, 10))</code></pre>
<p><img src="projecten_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<pre class="r"><code>#Plot Sleep sleep quality
ggplot(data=df3, aes(x=`Sleep_Quality(1-10)`, y=`Daily_Screen_Time(hrs)`, group=1)) +
  geom_line(color=&quot;red&quot;)+
  geom_point() +
  ylab(&quot;Daily screen time(hrs)&quot;) +
  xlab(&quot;Sleep quality&quot;) +
  ylim(c(0, 10)) +
  xlim(c(2, 10))</code></pre>
<p><img src="projecten_files/figure-html/unnamed-chunk-17-2.png" width="672" /></p>
<pre class="r"><code>#Plot stress levels
ggplot(data=df4, aes(x=`Stress_Level(1-10)`, y=`Daily_Screen_Time(hrs)`, group=1)) +
  geom_line(color=&quot;green&quot;)+
  geom_point() +
  ylab(&quot;Daily screen time(hrs)&quot;) +
  xlab(&quot;Stress level&quot;) +
  ylim(c(0, 10)) +
  xlim(c(2, 10))</code></pre>
<p><img src="projecten_files/figure-html/unnamed-chunk-17-3.png" width="672" /></p>
<p>In the xy-scatter plots of the 3 health indicators clear correlation
between average daily screen time and the mental health factor can be
seen. In the plots of happiness and sleep quality can be observed that
as the average daily screen time declines the happiness index becomes
higher. While stress levels rise when the average daily screen time goes
up.</p>
</div>
<div
id="specific-social-media-platform-with-the-highest-average-screen-time"
class="section level2">
<h2>Specific social media platform with the highest average screen
time</h2>
<p>To identify which of the social media platforms had the highest
average screen time, first a dataframe with the average screen time of
every measured social media platform was made.</p>
<pre class="r"><code>df6 &lt;- df1 %&gt;%
  group_by(`Social_Media_Platform`) %&gt;%
  summarise(across(`Daily_Screen_Time(hrs)`, mean)) 
df6</code></pre>
<pre><code>## # A tibble: 6 × 2
##   Social_Media_Platform `Daily_Screen_Time(hrs)`
##   &lt;chr&gt;                                    &lt;dbl&gt;
## 1 Facebook                                  5.66
## 2 Instagram                                 6.08
## 3 LinkedIn                                  5.29
## 4 TikTok                                    5.46
## 5 X (Twitter)                               5.31
## 6 YouTube                                   5.48</code></pre>
<p>To visualize the data a bar and pie chart were made. With these type
of graphs the difference between the Social media platforms can be
better interpreted.</p>
<pre class="r"><code>plot3 &lt;- df6 %&gt;% ggplot(aes(x = Social_Media_Platform, y = `Daily_Screen_Time(hrs)`)) +
  geom_bar(stat=&quot;identity&quot;, fill=&quot;steelblue&quot;) +
  labs(title=&quot;Average daily screen time for each social media platform&quot;) +
  ylab(&quot;Average daily screen time(hrs)&quot;) +
  xlab(&quot;Social media platform&quot;) +
  theme(axis.text.x = element_text(angle = 90, hjust=1, vjust=0.5)) + 
  scale_y_continuous(breaks = seq(0, 6, by = 1)) 
plot3</code></pre>
<p><img src="projecten_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>To make the data more interpretative a pie chart was also made.</p>
<pre class="r"><code>piechart &lt;- df6 %&gt;%
  ggplot(aes(x = &quot;&quot;, y = `Daily_Screen_Time(hrs)`, fill = Social_Media_Platform)) +
  geom_col(color = &quot;black&quot;) +
  coord_polar(&quot;y&quot;, start=0) +
  guides(fill = guide_legend(title = &quot;Social media platform&quot;)) +
  labs(title=&quot;Average daily screen time for each social media platform&quot;) +
  theme_void() 
piechart</code></pre>
<p><img src="projecten_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>In all of the charts can be seen that Instagram has the highest
average screen time for all the participants. Tik tok and facebook are
also platforms which have a high amount of screen time. The differences
are not very large. Instagram is only used 0,34 hours more than the
second highest facebook. On average each social media platform was used
for more than 5 hours a day.</p>
</div>
<div
id="identifying-the-participant-with-the-highest-and-lowest-amount-of-daily-screen-time-and-their-mental-health-state."
class="section level2">
<h2>Identifying the participant with the highest and lowest amount of
daily screen time and their mental health state.</h2>
<p>To find which of the participants had the highest amount of screen
time and worst mental state, there could be used multiple methods. By
first using MIN MAX and XLOOKUP for finding the participant.</p>
<p>Finding the row with the highest amount of daily screen time</p>
<pre class="r"><code>df1 %&gt;%
  filter(`Daily_Screen_Time(hrs)` == max(`Daily_Screen_Time(hrs)`))</code></pre>
<pre><code>## # A tibble: 2 × 10
##   User_ID   Age Gender `Daily_Screen_Time(hrs)` `Sleep_Quality(1-10)`
##   &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;                     &lt;dbl&gt;                 &lt;dbl&gt;
## 1 U249       46 Female                     10.8                     5
## 2 U326       27 Male                       10.8                     2
## # ℹ 5 more variables: `Stress_Level(1-10)` &lt;dbl&gt;,
## #   Days_Without_Social_Media &lt;dbl&gt;, `Exercise_Frequency(week)` &lt;dbl&gt;,
## #   Social_Media_Platform &lt;chr&gt;, `Happiness_Index(1-10)` &lt;dbl&gt;</code></pre>
<p>There seem to be two users with the exact same amount of Daily
maximum screen time;U249 and U326. These users have both a daily screen
time of 10,8 hours.</p>
<p>Finding the row with the lowest amount of screen time</p>
<pre class="r"><code>df1 %&gt;%
  filter(`Daily_Screen_Time(hrs)` == min(`Daily_Screen_Time(hrs)`))</code></pre>
<pre><code>## # A tibble: 2 × 10
##   User_ID   Age Gender `Daily_Screen_Time(hrs)` `Sleep_Quality(1-10)`
##   &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;                     &lt;dbl&gt;                 &lt;dbl&gt;
## 1 U040       23 Female                        1                     9
## 2 U095       41 Female                        1                     7
## # ℹ 5 more variables: `Stress_Level(1-10)` &lt;dbl&gt;,
## #   Days_Without_Social_Media &lt;dbl&gt;, `Exercise_Frequency(week)` &lt;dbl&gt;,
## #   Social_Media_Platform &lt;chr&gt;, `Happiness_Index(1-10)` &lt;dbl&gt;</code></pre>
<p>There seem to be also two users who have the lowest amount of screen
time of all the participant, User 040 and 095. These users have daily
screen time of 1 hour a day.</p>
<p>Now there has to be found out if users with the highest daily screen
time is the same when arranging from highest to lowest.</p>
<p>Arranging from highest to lowest daily screen time</p>
<pre class="r"><code>df7 &lt;- df1 %&gt;%
  arrange(desc(`Daily_Screen_Time(hrs)`))
df7</code></pre>
<pre><code>## # A tibble: 500 × 10
##    User_ID   Age Gender `Daily_Screen_Time(hrs)` `Sleep_Quality(1-10)`
##    &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;                     &lt;dbl&gt;                 &lt;dbl&gt;
##  1 U249       46 Female                     10.8                     5
##  2 U326       27 Male                       10.8                     2
##  3 U203       48 Female                     10                       3
##  4 U213       17 Female                      9.8                     4
##  5 U057       38 Female                      9.7                     3
##  6 U077       48 Female                      9.7                     4
##  7 U389       40 Male                        9.7                     4
##  8 U441       17 Female                      9.5                     4
##  9 U242       32 Male                        9.4                     3
## 10 U476       26 Female                      9.3                     3
## # ℹ 490 more rows
## # ℹ 5 more variables: `Stress_Level(1-10)` &lt;dbl&gt;,
## #   Days_Without_Social_Media &lt;dbl&gt;, `Exercise_Frequency(week)` &lt;dbl&gt;,
## #   Social_Media_Platform &lt;chr&gt;, `Happiness_Index(1-10)` &lt;dbl&gt;</code></pre>
<p>It indeed are the same two users who have the highest amount of daily
screen time.</p>
<p>Arranging from lowest to highest amount daily screen time</p>
<pre class="r"><code>df8 &lt;- df1 %&gt;%
  arrange(`Daily_Screen_Time(hrs)`)
df8</code></pre>
<pre><code>## # A tibble: 500 × 10
##    User_ID   Age Gender `Daily_Screen_Time(hrs)` `Sleep_Quality(1-10)`
##    &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;                     &lt;dbl&gt;                 &lt;dbl&gt;
##  1 U040       23 Female                      1                       9
##  2 U095       41 Female                      1                       7
##  3 U283       38 Female                      1.5                     9
##  4 U379       23 Male                        1.5                     9
##  5 U295       30 Female                      1.7                     9
##  6 U325       18 Male                        1.7                     9
##  7 U150       34 Female                      1.8                     9
##  8 U028       36 Female                      2                       8
##  9 U051       25 Female                      2                       9
## 10 U261       47 Female                      2.1                     8
## # ℹ 490 more rows
## # ℹ 5 more variables: `Stress_Level(1-10)` &lt;dbl&gt;,
## #   Days_Without_Social_Media &lt;dbl&gt;, `Exercise_Frequency(week)` &lt;dbl&gt;,
## #   Social_Media_Platform &lt;chr&gt;, `Happiness_Index(1-10)` &lt;dbl&gt;</code></pre>
<p>It indeed are the same two users who have the lowest amount of daily
screen time.</p>
</div>
<div id="conclusion-and-discussion" class="section level2">
<h2>Conclusion and Discussion</h2>
<p>The analysis of the dataset mental health and social media habits
with 500 users, contained some interesting results. This analysis had
multiple aims, all trying to find out the correlation between mental
health and social media habits. Identification of the user group with
the highest amount of average daily screen time. Here there was sorted
between 3 different genders. Male, female and others. In the results of
this analysis the group with the highest amount of average screen time
was Males. The difference between the genders was not very large,
especially the difference between males and females was small. The
minimum and maximum value of average daily screen time was ranging from
1-10.8 hours. Both top end bottom 2 of the dataset could be succesfully
identified using filtering and sorting.</p>
<p>The social media platform with the highest effect on the screen time
of the users was successfully identified in this analysis. Instagram had
the highest average screen time for all of the users. Instagram had an
average daily screen time of 6,08 hours per day. Instagram was followed
by Facebook and Tiktok for second and third highest. All social media
platforms had an average daily screen time of 5 hours.</p>
<p>To find the correlation between social media usage and mental health,
3 different health factors were measured. The results for these were
very interesting. In the analysis 3 xy-scatter plots were made by
plotting the average daily screen time, against 1 of the 3 health
indicators. In the graphs, could be seen that stress levels go up when
the daily screen time rises. Sleep quality and happiness go down as the
screen becomes less. So screen time has a negative effect on happiness
and sleep quality and increases stress levels.</p>
<p>There can be concluded that social media exposure and screen time
have a negative effect on the mental wellbeing of the users in this
analysis. The analysis could be expanded and more research should be
done in the future about the negative effects of social media on mental
health.</p>
</div>
<div id="checklist" class="section level2">
<h2>checklist</h2>
<div class="float">
<img src="checklist_R.png" alt="data" />
<div class="figcaption">data</div>
</div>
<p>• Checklist is complete</p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
